# Matrices

A matrix is an array of numbers organized as a table:

$$
\boldsymbol{A} = 
\begin{bmatrix}
3.14159 & 2.71828 \\
1.41421 & 42
\end{bmatrix}
$$

We will use boldface capital letters for matrices. This particular matrix has $2$ rows and $2$ columns. If a matrix $\boldsymbol{M}$ has $m$ rows and $n$ columns we indicate this as follows:

- $\boldsymbol{M}_{m \times n}$
- $\boldsymbol{M} \in \mathbb{R}^{m \times n}$ ($\boldsymbol{M}$ belong to the set of real-valued matrices of size $m$ by $n$)
- $\boldsymbol{M} \in \mathcal{M}_{m, n}(\mathbb{R})$ (same as above)

So, for instance, to indicate the size of the matrix $\boldsymbol{A}$ above we can write $\boldsymbol{A}_{2 \times 2}$, $\boldsymbol{A} \in \mathbb{R}^{2 \times 2}$, or $\boldsymbol{A} \in \mathcal{M}_{2, 2}(\mathbb{R}$)

Each element position can be identified by two integer indices starting at one and indicating the row and column of the element. They are written as subscripts to the matrix name:

$$
\begin{align*}
\boldsymbol{A}_{1, 1} & = 3.14159 \text{ (a few digits of } \pi \text{ at row } 1 \text{ and column } 1 \text{)}\\
\boldsymbol{A}_{1, 2} & = 2.71828 \text{ (a few digits of } e \text{ at row } 1 \text{ and column } 2 \text{)}\\
\boldsymbol{A}_{2, 1} & = 1.41421 \text{ (a few digits of } \sqrt{2} \text{ at row } 2 \text{ and column } 1 \text{)}\\
\boldsymbol{A}_{2, 2} & = 42 \text{ (``The Answer to the Ultimate Question of Life, The Universe, and Everything'' at row } 2 \text{ and column } 2 \text{)}
\end{align*}
$$

Sometimes we use lowercase letters corresponding to the matrix name as well:

$$
\begin{align*}
a_{1, 1} & = 3.14159 \\
a_{1, 2} & = 2.71828 \\
a_{2, 1} & = 1.41421 \\
a_{2, 2} & = 42
\end{align*}
$$

It's the same thing.



---

**Exercise** For the matrix below identify what is asked.

$$
\boldsymbol{C} = 
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

(a) The size, using one of the notations above

(b) The element $\boldsymbol{C}_{2, 2}$

(c) The element $c_{1, 3}$

---

Sometimes we want to be able to specify a matrix in a more abstract way, by defining its elements with formulas. For example, if I define the matrix $\boldsymbol{A}$ like this:

$$
\boldsymbol{A}_{m \times n} = 
\begin{bmatrix}
a_{i, j}
\end{bmatrix} \text{ such that } a_{i, j} = 10 i + j^2
$$

that means

$$
\boldsymbol{A}_{2 \times 3} = 
\begin{bmatrix}
11 & 14 & 19 \\
21 & 24 & 29
\end{bmatrix}
$$


---

**Exercise** Write the following matrices:

(a) $\boldsymbol{A}_{2 \times 2} = [a_{i,j}] \text{ such that } a_{i,j} = 7$

(b) $\boldsymbol{A}_{4 \times 4} = [a_{i,j}] \text{ such that } a_{i,j} = 1 \text{ if } i = j \text{ and zero otherwise}$

---

**Exercise** For

$$
\boldsymbol{A}_{2 \times 2} = \left[a_{i,j}\right] =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

write $\boldsymbol{B}_{2 \times 2} = \left[b_{i, j}\right]$ such that $b_{i,j} = a_{j, i}$

---

Some terminology:

- A matrix of just one row is called a "row-matrix". Row-matrices have just one effective index (the column index), and therefore are very analogous to standard $\mathbb{R}^{n}$ vectors. For this reason, sometimes we use lowercase letters for row-matrices (breaking the rule of uppercase letters for matrices). For instance:

$$
\boldsymbol{u} =
\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}
$$

- A matrix of just one column is called a "column-matrix". For the same reasons as those of the row-matrix, a column-matrix is usually seen as a vector, and written with lowercase letters. For example:

$$
\boldsymbol{v} = 
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}
$$

- A matrix with the same number of rows and columns is called a "square matrix"

Matrices are very useful:

- You can store data: spreadsheets, images, etc
- You can represent connectivity data, such as networks
- You can represent linear transformations

For instance, if we have the data as follows:

- Tarfield eats 5 lasanhas and 3 apple pies a day. 
- Ton eats 1 lasanha and 1 salad.

We can represent this information in a matrix:

$$
\boldsymbol{H} = 
\begin{bmatrix}
5 & 3 & 0 \\
1 & 0 & 1
\end{bmatrix}
$$

where $\boldsymbol{H}_{2 \times 3}$ is the matrix of eating habits of Tarfield and Ton, the rows represent the characters (row $1$: Tarfield, row $2$: Ton) and the columns represent the dishes (column $1$: lasanha, column $2$: apple pie, column $3$: salad).


---

**Exercise** Bananas have $420$ mg of potassium, $27$ g of carbohydrates, and $1.3$ g of protein. Apples have $200$ mg of potassium, $25$ g of carbs and $0.5$ g of protein. Represent this information in a matrix where rows are nutrients and columns are fruits.

---

In Python we can use the library `numpy` to handle matrices:

In [1]:
import numpy as np

For a review of `numpy` consult the documentation: https://numpy.org/doc/stable/ (hint: try the "Getting Started" guide, it is really good!)

and this useful notebook by Aurélien Geron (the author of this course's textbook): https://github.com/ageron/handson-ml3/blob/main/tools_pandas.ipynb

The effort to cover library details is both too much and too redundant with the good references above. So, from now on I'll make few examples of code, but by far and large I'll assume that you went through the references I provided to make yourself acquinted with the library, ok?

Our little example matrix $\boldsymbol{A}$ above can be made in several ways in `numpy`. We could start with an empty matrix and fill it up:

In [2]:
# Make a 2x2 matrix of zeros.
A = np.zeros((2, 2))
print(A)

# Fill it up.
A[0, 0] = 3.14159
A[0, 1] = 2.71828
A[1, 0] = 1.41421
A[1, 1] = 42
print(A)


[[0. 0.]
 [0. 0.]]
[[ 3.14159  2.71828]
 [ 1.41421 42.     ]]


Notice an important detail: while mathematicians prefer to start numbering their rows and columns from one, computer programmers often prefer to start at zero. So, in Mathematics we have $\boldsymbol{A}_{1,1}$, in `numpy` we have `A[0, 0]`.

A more direct way of making a matrix of known values is shown below:

In [3]:
A = np.array([[3.14159, 2.71828], [1.41421, 42]])
print(A)

[[ 3.14159  2.71828]
 [ 1.41421 42.     ]]



---

**Exercise** Write the matrix $\boldsymbol{C}$ in `numpy`:

$$
\boldsymbol{C} = 
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

---

Numpy allows us to make matrices with random values easily. For instance, here is a $3 \times 4$ matrix with random integers from $1$ to $100$:

In [4]:
X = np.random.randint(low=1, high=100, size=(3, 4))
X

array([[15, 37, 40, 37],
       [30, 29, 47, 85],
       [66, 31, 86, 27]], dtype=int32)

And here is a $4 \times 2$ matrix of normal-distributed values with $\mu = 5.2$ and $\sigma = 2.3$:

In [5]:
X = np.random.normal(loc=5.2, scale=2.3, size=(4, 2))
X

array([[7.02098149, 4.16994217],
       [4.17292636, 7.0166654 ],
       [4.35272898, 4.21790614],
       [7.29269101, 2.69320988]])

Sometimes we have to select a "submatrix" from the larger one. In Numpy we can use the familiar "slicing" notation of Python:

In [6]:
X = np.linspace(start=1, stop=20, num=20).reshape(4, 5)
X

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [7]:
i_1 = 1  # Take from row index 1 (the second row).
i_2 = 4  # Take up to the row BEFORE index 4 (that is, go up to row index 3, the last one).
j_1 = 0  # Take from column index 0 (the first column).
j_2 = 2  # Take up to the column BEFORE index 2 (that is, go up to column index 1).

X[i_1:i_2, j_1:j_2]

array([[ 6.,  7.],
       [11., 12.],
       [16., 17.]])

When you want to go all the way to the end, or start from the very beginning, you don't need to write the corresponding index:

In [8]:
X[i_1:, :j_2]

array([[ 6.,  7.],
       [11., 12.],
       [16., 17.]])

If you want the entire range, you can skip both indices:

In [9]:
X[:, 1:2]  # Take the entire second column.

array([[ 2.],
       [ 7.],
       [12.],
       [17.]])

CAREFUL: the operation below will reduce the dimensionality of the array:

In [10]:
X[:, 1]  # Take the entire second column as a 1D array.

array([ 2.,  7., 12., 17.])

 so a matrix becomes a vector! If you want to select the column and keep it as a column matrix (which is what you want to do most of the time), you have to `.reshape()` the result:

In [11]:
X[:, 1].reshape(-1, 1)  # Take the entire second column and reshape it to be a column vector.

array([[ 2.],
       [ 7.],
       [12.],
       [17.]])

Better to always use the full notation.

We will use a similar notation for slicing matrices in pure Mathematics, but with the following differences:

- We start indexing at one
- We include both ends of the indexing (Numpy excludes the final index value)

So, for example, if 

$$
\boldsymbol{X} = 
\begin{bmatrix}
 1 &  2 &  3 &  4 &  5 \\
 6 &  7 &  8 &  9 & 10 \\
11 & 12 & 13 & 14 & 15 \\
16 & 17 & 18 & 19 & 20 \\
\end{bmatrix}
$$

then

$$
\boldsymbol{X}_{2:3, 2:4} = 
\begin{bmatrix}
 7 &  8 &  9 \\
12 & 13 & 14 \\
\end{bmatrix},
\boldsymbol{X}_{:, :2} = 
\begin{bmatrix}
 1 &  2 \\
 6 &  7 \\
11 & 12 \\
16 & 17 \\
\end{bmatrix}, \text{ etc.}
$$


---

**Exercise** Write both the slicing notation for mathematical matrices and the Numpy notation for `numpy` arrays for the following submatrices of a given matrix $\boldsymbol{M} \in \mathbb{R}^{m \times n}$:

(a) The range of data between rows $3$ and $7$, and columns $2$ and $5$

(b) The first column

(c) The last row

---

## Matrix operations

### Matrix transposition

The transpose of a matrix $\boldsymbol{A}_{m \times n}$ is a matrix $\boldsymbol{B}_{n \times m}$ that is obtained exchanging row and column indices: $b_{i, j} = a_{j, i}$. There is a special notation for the transpose of a matrix: apply the superscript $T$ to it, so instead of naming the transpose of $\boldsymbol{A}$ as some other name $\boldsymbol{B}$, it is better to write $\boldsymbol{A}^{T}$.

$$
\boldsymbol{A} = 
\begin{bmatrix}
\color{red}{a_{1,1}} & \color{red}{a_{1,2}} & \color{red}{\cdots} & \color{red}{a_{1,n}} \\
a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m,1} & a_{m,2} & \cdots & a_{m,n} \\
\end{bmatrix}
\Rightarrow
\boldsymbol{A}^{T} = 
\begin{bmatrix}
\color{red}{a_{1,1}} & a_{2,1} & \cdots & a_{m,1} \\
\color{red}{a_{1,2}} & a_{2,2} & \cdots & a_{m,2} \\
\color{red}{\vdots} & \vdots & \ddots & \vdots \\
\color{red}{a_{1,n}} & a_{2,n} & \cdots & a_{m,n} \\
\end{bmatrix}
$$

### Matrix sum

Two matrices can be added together if they have the same shape. The sum of two matrices is the matrix formed by adding the corresponding elements of each matrix. For example:

$$
\boldsymbol{A} = 
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}, \;
\boldsymbol{B} = 
\begin{bmatrix}
-1 & -2 \\
3 & 4 \\
0 & 0
\end{bmatrix}
\Rightarrow
\boldsymbol{A} + \boldsymbol{B} = 
\begin{bmatrix}
0 & 0 \\
6 & 8 \\
5 & 6
\end{bmatrix}
$$

### Scalar multiplication

A matrix can be multiplied by a scalar, which multiplies each element of the matrix by that scalar. For example:

$$
\boldsymbol{A} = 
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}, \; 
\alpha = 10
\Rightarrow
\alpha \boldsymbol{A} = 
\begin{bmatrix}
10 & 20 \\
30 & 40 \\
50 & 60 \\
\end{bmatrix}
$$

By the way, with scalar multiplication and matrix sum we fit the criteria for a *vector space*: matrices are vectors too! We have the following properties for matrix sum and scalar multiplication (assume compatible shapes whenever necessary):

(Sum properties)

1. Matrix sum is commutative: $\boldsymbol{A} + \boldsymbol{B} = \boldsymbol{B} + \boldsymbol{A}$

2. Matrix sum is associative: $(\boldsymbol{A} + \boldsymbol{B}) + \boldsymbol{C} = \boldsymbol{A} + (\boldsymbol{B} + \boldsymbol{C})$

3. There exists the *null matrix* $\boldsymbol{0} \in \mathbb{R}^{m \times n}$ such that $\boldsymbol{A} + \boldsymbol{0} = \boldsymbol{A}$. It is just the matrix made of zeros.

4. For every matrix $\boldsymbol{A}$ there is an *additive inverse* (or simply, its *negative*), denoted $-\boldsymbol{A}$, such that $\boldsymbol{A} + (-\boldsymbol{A}) = \boldsymbol{0}$

(Scalar multiplication properties)

5. Scalar multiplication is distributive with respect to the scalar sum: $(\alpha + \beta) \boldsymbol{A} = \alpha \boldsymbol{A} + \beta \boldsymbol{A}$

6. Scalar multiplication is distributive with respect to the matrix sum: $\alpha (\boldsymbol{A} + \boldsymbol{B}) = \alpha \boldsymbol{A} + \alpha \boldsymbol{B}$

7. Scalar multiplication is associative: $\alpha (\beta \boldsymbol{A}) = (\alpha \beta) \boldsymbol{A}$

8. Multiplying by $1$ does nothing: $1 \boldsymbol{A} = \boldsymbol{A}$


---

**Exercise** For the matrices $\boldsymbol{A}$ and $\boldsymbol{B}$ above, write:

(a) $5 \boldsymbol{A} + 3 \boldsymbol{B}$

(b) $\boldsymbol{A} - \boldsymbol{A}$

(c) $0 \boldsymbol{B}$

---

**Exercise** Repeat the previous exercise with Numpy.

---

**Exercise** Construct numerical examples of each property above using Numpy.

---

**Exercise** My online store sell pens and notebooks (the paper kind) through two different marketplaces: Rainforest and oBey. In January we sold products as follows:

|           | Rainforest | oBey  |
|-----------|------------|-------|
| pens      | 12,345     | 5,432 |
| notebooks | 2,345      | 1,234 |

Curiously, every month after that my sales increased $10%$ with respect to the previous month! I had to close the store by the end of December, that's how afraid I am of exponential success! :)

(a) Represent January sales as a matrix.

(b) Represent as a matrix expression (scalar multiplication and matrix summations) the entire set of sales for the $12$ months.

(c) How much did I sell of each product in each marketplace after my short run as an entrepreneur?

---

### Matrix multiplication

Matrix multiplication has a very weird definition. Let's start with the definition, then get a feeling for the meaning.

Two matrices $\boldsymbol{A} \in \mathbb{R}^{m \times p}$ and $\boldsymbol{B} \in \mathbb{R}^{p \times n}$ can be multiplied if the shapes are compatible: the number of columns of the first matrix matches the number of rows of the second matrix. The resulting matrix $\boldsymbol{C} = \boldsymbol{A} \boldsymbol{B}$ will have shape $m \times n$, that is, the number of rows of the first for its own number of rows, and the number of columns of the second for its own number of columns: $\boldsymbol{C} \in \mathbb{R}^{m \times n}$.

<img src="matprod.png" width=25%/>

The matrix multiplication operation is defined as:

$$
\boldsymbol{C}_{m \times n} = \boldsymbol{A}_ {m \times p} \boldsymbol{B}_{p \times n}
\Rightarrow
c_{i,j} = \sum_{k=1}^{p} a_{i, k} b_{k, j}
$$

This is the familiar "row times column" rule that you learned in high school.

<img src="matprod_dot.png" width=50%/>

It is like doing the dot product between the $i$-th row of $\boldsymbol{A}$ and the $j$-th column of $\boldsymbol{B}$.

But what is the real meaning of a matrix multiplication? In order to explore this, let's consider the multiplication of a matrix $\boldsymbol{A} \in \mathbb{R}^{m \times n}$ by a column-matrix $\boldsymbol{v} \in \mathbb{R}^{n}$:

<img src="matvec_1.png" width=50%/>

If we look at the columns of $\boldsymbol{A}$ as vectors $\boldsymbol{a}^{(i)}$ (we will drop the arrows for vectors and use boldface instead, so row and column matrices are interchangeable with vectors), and look at $\boldsymbol{v}$ as column-matrix, then the result $\boldsymbol{u} = \boldsymbol{A} \boldsymbol{v}$ is a linear combination of the columns of $A$:

<img src="matvec_2.png" width=50%/>

So, in this view, matrix multiplication is the same as *forming linear combinations*. If instead of a column-matrix $\boldsymbol{v}$ we had a full matrix $\boldsymbol{V}$ the same logic applies, once per column of $\boldsymbol{V}$.


---

**Exercise** In a previous exercise we had the information that:

- Bananas have $420$ mg of potassium, $27$ g of carbohydrates, and $1.3$ g of protein. 
- Apples have $200$ mg of potassium, $25$ g of carbs and $0.5$ g of protein.

Kevin likes to eat $5$ bananas and $3$ apples a day, while Stuart likes to eat $2$ bananas and $4$ apples a day. 

(a) You already wrote the nutritional information of the fruits as a matrix of nutrients (rows) per fruits (columns). Now write the eating preferences (quantity of fruit per day) of Kevin and Stuart as a matrix of fruits (rows) per character (columns)

(b) You now have two matrices: $\boldsymbol{F}_{\text{nutrients} \times \text{fruits}}$ and $\boldsymbol{P}_{\text{fruits} \times \text{characters}}$. Write the matrix product that allows us to obtain the amount of nutrients per character.

---

In Numpy the matrix multiplication is performed by the operator `@`:

In [12]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A @ B
D = B @ A

print(C)
print(D)

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


### Properties of matrix multiplication

**Matrix multiplication is *NOT* commutative**

Often one cannot even form the reverse product due to the shapes! For example, if $\boldsymbol{A} \in \mathbb{R}^{2 \times 3}$ and $\boldsymbol{B} \in \mathbb{R}^{3 \times 4}$ then $\boldsymbol{A} \boldsymbol{B}$ is doable, but $\boldsymbol{B} \boldsymbol{A}$ is not due to the shapes of the matrices.

Even if the reverse product is doable, generally we have $\boldsymbol{A} \boldsymbol{B} \neq \boldsymbol{B} \boldsymbol{A}$. First of all, the shapes of $\boldsymbol{A} \boldsymbol{B}$ and $\boldsymbol{B} \boldsymbol{A}$ may not match: if $\boldsymbol{A} \in \mathbb{R}^{2 \times 3}$ and $\boldsymbol{B} \in \mathbb{R}^{3 \times 2}$ then $(\boldsymbol{A} \boldsymbol{B}) \in \mathbb{R}^{2 \times 2}$ and $(\boldsymbol{B} \boldsymbol{A}) \in \mathbb{R}^{3 \times 3}$

Second, even if the reverse product is doable and the shapes match (only possible for square matrices $\boldsymbol{A}$ and $\boldsymbol{B}$), we still usually do not have commutativity. For instance:

$$
\boldsymbol{A} = 
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}, \;
\boldsymbol{B} = 
\begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
\Rightarrow
\boldsymbol{A} \boldsymbol{B} = 
\begin{bmatrix}
19 & 22 \\
43 & 50
\end{bmatrix}, \;
\boldsymbol{B} \boldsymbol{A} = 
\begin{bmatrix}
23 & 34 \\
31 & 46 \\
\end{bmatrix}
\Rightarrow
\boldsymbol{A} \boldsymbol{B} \neq \boldsymbol{B} \boldsymbol{A}
$$

**Matrix multiplication is associative**

$\boldsymbol{A} (\boldsymbol{B} \boldsymbol{C}) = (\boldsymbol{A} \boldsymbol{B}) \boldsymbol{C}$

**Matrix multiplication is distributive with the matrix sum**

And it is distributive on both the left and right sides: $\boldsymbol{A} (\boldsymbol{B} + \boldsymbol{C}) = \boldsymbol{A} \boldsymbol{B} + \boldsymbol{A} \boldsymbol{C}$ and $(\boldsymbol{A} + \boldsymbol{B}) \boldsymbol{C} = \boldsymbol{A} \boldsymbol{C} + \boldsymbol{B} \boldsymbol{C}$.

**Scalar multiplication is associative with matrix multiplication**

$\alpha (\boldsymbol{A} \boldsymbol{B}) = (\alpha \boldsymbol{A}) \boldsymbol{B} = \boldsymbol{A} (\alpha \boldsymbol{B})$

**The transpose of a product is the reverse product of the transposes**

$(\boldsymbol{A} \boldsymbol{B})^T = \boldsymbol{B}^T \boldsymbol{A}^T$

**There is a square matrix that does nothing in multiplication: the identity matrix**

The square matrix below is a *diagonal* matrix (that is, a square matrix where all elements are zero except those with the same row and column index - the elements in the main diagonal) with ones in the diagonal:

$$
\boldsymbol{I}_{n \times n} = 
\begin{bmatrix}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & 1
\end{bmatrix}
$$

This is the *identity matrix* of size $n$. Any matrix $\boldsymbol{M} \in \mathbb{R}^{n \times p}$ that gets multiplied by the identity matrix results in the very same matrix $\boldsymbol{M}$!

$$
\boldsymbol{I} \boldsymbol{M} = \boldsymbol{M}
$$


---

**Exercise** Construct numerical examples of each property using Numpy. For transposition of a matrix `X` use `X.T`. For the identity matrix, use `np.eye(n)`.

---

### Block matrix multiplication

An extremely useful property of matrix multiplication is that you can do it "in blocks"! What does it mean? Suppose you have big matrices $\boldsymbol{A}$ and $\boldsymbol{B}$ that you wish to multiply together:

<img src="block_matrices_01.png" width=50%/>

Let's partition the matrices into blocks in any way we want, as long as:

- The number of blocks in the row direction and in the column direction of each matrix obey the rule for the shapes of matrices being multiplied. For instance, we can partition $\boldsymbol{A}$ into $3$ blocks vertically and $2$ blocks horizontally, and $\boldsymbol{B}$ into $2$ block vertically (so that we respect the matrix multiplication shape rules) and $4$ blocks horizontally.

<img src="block_matrices_02.png" width=50%>

- The blocks themselves have shapes that allow the inner block multiplication to happen. See the grid in the image above, and how it respects the shapes of the inner blocks!

Now construct the blocks by applying the matrix multiplication to the partitioned matrix! So, in the example:

$$
\begin{align*}
\boldsymbol{C}^{(1,1)} & = \boldsymbol{A}^{(1,1)} \boldsymbol{B}^{(1,1)} + \boldsymbol{A}^{(1,2)} \boldsymbol{B}^{(2,1)} \\
\boldsymbol{C}^{(1,2)} & = \boldsymbol{A}^{(1,1)} \boldsymbol{B}^{(1,2)} + \boldsymbol{A}^{(1,2)} \boldsymbol{B}^{(2,2)} \\
& \vdots \\
\boldsymbol{C}^{(3,4)} & = \boldsymbol{A}^{(3,1)} \boldsymbol{B}^{(1,4)} + \boldsymbol{A}^{(3,2)} \boldsymbol{B}^{(2,4)} \\
\end{align*}
$$

Let's make a numerical example: suppose we want to multiply matrices $\boldsymbol{A}$ and $\boldsymbol{B}$ as below:

<img src="block_matrices_03.png" width=33%>

We can partition these matrices into blocks as follows:

<img src="block_matrices_04.png" width=33%>

Now the block multiplications are easier:

$$
\begin{align*}
\boldsymbol{C}^{(1,1)} & =
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix}
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix}
+
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
\begin{bmatrix}
0 & 0
\end{bmatrix}
= 
\begin{bmatrix}
7 & 10 \\
15 & 22 \\
\end{bmatrix}
+
\begin{bmatrix}
0 & 0 \\
0 & 0 \\
\end{bmatrix}
=
\begin{bmatrix}
7 & 10 \\
15 & 22 \\
\end{bmatrix} \\
\boldsymbol{C}^{(1,2)} & =
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix}
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
+
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
\begin{bmatrix}
5 \\
\end{bmatrix}
=
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
+
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
=
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix} \\
\boldsymbol{C}^{(2,1)} & =
\begin{bmatrix}
0 & 0
\end{bmatrix}
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
\end{bmatrix}
+
\begin{bmatrix}
5 \\
\end{bmatrix}
\begin{bmatrix}
0 & 0
\end{bmatrix}
= 
\begin{bmatrix}
0 & 0
\end{bmatrix}
+
\begin{bmatrix}
0 & 0
\end{bmatrix}
=
\begin{bmatrix}
0 & 0
\end{bmatrix} \\
\boldsymbol{C}^{(2,2)} & =
\begin{bmatrix}
0 & 0
\end{bmatrix}
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
+
\begin{bmatrix}
5 \\
\end{bmatrix}
\begin{bmatrix}
5 \\
\end{bmatrix}
=
\begin{bmatrix}
0 \\
\end{bmatrix}
+
\begin{bmatrix}
25 \\
\end{bmatrix}
=
\begin{bmatrix}
25 \\
\end{bmatrix}
\end{align*}
$$

And then we put the result together:

<img src="block_matrices_05.png" width=40%>

Block multiplication is very useful in several scenarios:

- It allows easy multiplication of matrices in particular (and quite common) cases, such as "block-diagonal" matrices.

- We can multiply massive matrices that may not even fit in memory, by loading smaller blocks, performing operations on them, and recomposing the result later.

- In many cases it is useful to look at matrices from a block standpoint, to get some interesting insights - more on this later.


---

**Exercise** In a previous exercise we had the information that:

- Bananas have $420$ mg of potassium, $27$ g of carbohydrates, and $1.3$ g of protein. 
- Apples have $200$ mg of potassium, $25$ g of carbs and $0.5$ g of protein.

Kevin likes to eat $5$ bananas and $3$ apples a day, while Stuart likes to eat $2$ bananas and $4$ apples a day. 

Representing all this information as a matrix multiplication we have:

<img src="minions_matprod.png" width=66%>

(a) Split $\boldsymbol{F}$ by columns and $\boldsymbol{P}$ by rows and express $\boldsymbol{N}$ as a block-matrix product. This way of computing $\boldsymbol{N}$ emphasizes the fruit contribution separately, by providing the nutrient per character as each parcel of a matrix sum. Do the computations using Numpy.

(b) Split $\boldsymbol{F}$ by rows and $\boldsymbol{P}$ by columns and express $\boldsymbol{N}$ as a block-matrix product. This way of computing $\boldsymbol{N}$ is the standard matrix product computation, and emphasizes the separate contributions of nutrients per character by abstracting the fruit itself. Do the computations using Numpy.

## Matrices as linear transformations

A linear transformation is a function $T: \mathbb{R}^{n} \rightarrow \mathbb{R}^{m}$ that maps vectors in $\mathbb{R}^{n}$ to vectors in $\mathbb{R}^{m}$ with the following properties:

1. Scaling a vector scales its transform: $T(\alpha \boldsymbol{v}) = \alpha T(\boldsymbol{v})$

2. The transform of the sum is the sum of the transforms: $T(\boldsymbol{u} + \boldsymbol{v}) = T(\boldsymbol{u}) + T(\boldsymbol{v})$

Linear transformations are **everywhere** - that's why Linear Algebra is so popular! Some examples:

- Consider the following electrical circuit:

<img src="circuit.png" width=33%/>

The relationship between the source voltages $(V_1, V_2)$ and the branch currents $(i_1, i_2, i_3)$ is given by:

$$
\begin{bmatrix}
i_1 \\
i_2 \\
i_3
\end{bmatrix}
=
\begin{bmatrix}
\phantom{-}\frac{2}{3} & -\frac{1}{3} \\[4pt]
-\frac{1}{3} & \phantom{-}\frac{2}{3} \\[4pt]
\phantom{-}\frac{1}{3} & \phantom{-}\frac{1}{3} \\
\end{bmatrix}
\begin{bmatrix}
V_1 \\
V_2
\end{bmatrix}
$$

So the vector of currents is given by a matrix times the vector of voltages: $\boldsymbol{i} = \boldsymbol{G} \boldsymbol{v}$. As such, the transformation from voltages to currents is a linear transformation.

In fact, ***any*** linear transformation can be represented as a matrix multiplication operation! 

Let $\boldsymbol{e}^{(i)} \in \mathbb{R}^n$, $i \in \{1, 2, \cdots, n\}$ be the vector with all zeros except for a $1$ in the $i$-th position, that is, if $n = 3$ for example we have:

$$
\boldsymbol{e}^{(1)} =
\begin{bmatrix}
1 \\
0 \\
0
\end{bmatrix}, \;
\boldsymbol{e}^{(2)} =
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}, \;
\boldsymbol{e}^{(3)} =
\begin{bmatrix}
0 \\
0 \\
1
\end{bmatrix}
$$

These special vectors have a name: *canonical basis vectors*. Now every vector in $\mathbb{R}^{n}$ is easily written as a linear combination of these guys: if a vector $\boldsymbol{v}$ has components $v_{i}$, $i \in \{1, 2, \cdots, n\}$, then $\boldsymbol{v} = v_1 \boldsymbol{e}^{(1)} + v_2 \boldsymbol{e}^{(2)} + \cdots + v_n \boldsymbol{e}^{(n)}$:

$$
\boldsymbol{v} = 
\begin{bmatrix}
v_1 \\
v_2 \\
\vdots \\
v_n
\end{bmatrix}
=
v_1
\begin{bmatrix}
1 \\
0 \\
\vdots \\
0
\end{bmatrix} +
v_2
\begin{bmatrix}
0 \\
1 \\
\vdots \\
0
\end{bmatrix} +
\cdots +
v_n
\begin{bmatrix}
0 \\
0 \\
\vdots \\
1
\end{bmatrix}
=
v_1 \boldsymbol{e}^{(1)} + v_2 \boldsymbol{e}^{(2)} + \cdots + v_n \boldsymbol{e}^{(n)}
$$

Consider a linear transformation $T: \mathbb{R}^{n} \rightarrow \mathbb{R}^{m}$ (we don't know that we can use a matrix for this, we just know that the transformation is linear). What do we get for $\boldsymbol{u} = T(\boldsymbol{v})?$ Since the transformation is linear:

$$
\begin{align*}
\boldsymbol{u} & = T(\boldsymbol{v}) \\
& = T(v_1 \boldsymbol{e}^{(1)} + v_2 \boldsymbol{e}^{(2)} + \cdots + v_n \boldsymbol{e}^{(n)}) \\
& = v_1 T(\boldsymbol{e}^{(1)}) + v_2 T(\boldsymbol{e}^{(2)}) + \cdots + v_n T(\boldsymbol{e}^{(n)})
\end{align*}
$$

Let's call $\boldsymbol{m}^{(i)} = T(\boldsymbol{e}^{(i)})$ the vector that we obtain transforming the $i$-th canonical basis vector. So the expression above becomes:

$$
\begin{align*}
\boldsymbol{u} & = v_1 T(\boldsymbol{e}^{(1)}) + v_2 T(\boldsymbol{e}^{(2)}) + \cdots + v_n T(\boldsymbol{e}^{(n)}) \\
& = v_1 \boldsymbol{m}^{(1)} + v_2 \boldsymbol{m}^{(2)} + \cdots + v_n \boldsymbol{m}^{(n)}
\end{align*}
$$

Now stack all $\boldsymbol{m}^{(i)}$ as columns of a matrix $\boldsymbol{M}$:

$$
\boldsymbol{M} = 
\begin{bmatrix}
\rule[-2ex]{0.5pt}{4ex} & \rule[-2ex]{0.5pt}{4ex} & & \rule[-2ex]{0.5pt}{4ex} \\[1pt]
\boldsymbol{m}^{(1)} & \boldsymbol{m}^{(2)} & \cdots & \boldsymbol{m}^{(n)} \\[1pt]
\rule[-2ex]{0.5pt}{4ex} & \rule[-2ex]{0.5pt}{4ex} & & \rule[-2ex]{0.5pt}{4ex} \\[1pt]
\end{bmatrix}
$$

Now we can write $\boldsymbol{u} = \boldsymbol{M} \boldsymbol{v}$ because:

$$
\begin{bmatrix}
\rule[-2ex]{0.5pt}{4ex} \\[1pt]
\boldsymbol{u} \\[1pt]
\rule[-2ex]{0.5pt}{4ex} \\[1pt]
\end{bmatrix}
=
\begin{bmatrix}
\rule[-2ex]{0.5pt}{4ex} & \rule[-2ex]{0.5pt}{4ex} & & \rule[-2ex]{0.5pt}{4ex} \\[1pt]
\boldsymbol{m}^{(1)} & \boldsymbol{m}^{(2)} & \cdots & \boldsymbol{m}^{(n)} \\[1pt]
\rule[-2ex]{0.5pt}{4ex} & \rule[-2ex]{0.5pt}{4ex} & & \rule[-2ex]{0.5pt}{4ex} \\[1pt]
\end{bmatrix}
\begin{bmatrix}
v_1 \\
v_2 \\
\vdots \\
v_n
\end{bmatrix}
$$

And we are done! Through the process above, any linear transformation can be converted into a matrix multiplication!


---

**Exercise** Consider a series of linear transformations that takes a vector $\boldsymbol{v} \in \mathbb{R}^{2}$ and applies the following steps:

($T_1$) Rotates the vector counter-clockwise by $30$ degrees, and

($T_2$) Scales the resulting vector by a factor of $2$ in the first coordinate and $0.5$ in the second coordinate, and \\

($T_3$) Rotates the vector clockwise by $30$ degrees.

For instance, follow the transformations below:

$$
\boldsymbol{v} = 
\begin{bmatrix}
1 \\
1
\end{bmatrix}
\overset{T_1}{\longrightarrow}
\begin{bmatrix}
0.366\\
1.366
\end{bmatrix}
\overset{T_2}{\longrightarrow}
\begin{bmatrix}
0.732\\
0.683
\end{bmatrix}
\overset{T_3}{\longrightarrow}
\begin{bmatrix}
0.975\\
0.225
\end{bmatrix}
$$

<img src="linear_transf.png" width=100%>

(a) Express $T_1$, $T_2$, and $T_3$ in matrix form.

(b) Express $T = (T_3 \circ T_2 \circ T_1)$ in matrix form.

**HINT**: For every transformation, think about what that particular transformation does to the *canonical basis vectors*:

$$
\boldsymbol{e}^{(1)} = 
\begin{bmatrix}
1 \\
0
\end{bmatrix}, \;
\boldsymbol{e}^{(2)} = 
\begin{bmatrix}
0 \\
1
\end{bmatrix}
$$

then assemble the transformation matrix as shown above.

---

## When is a linear transformation invertible?

A transformation $T: \mathbb{R}^{n} \to \mathbb{R}^{m}$ is invertible if every time I transform an arbitrary vector $\boldsymbol{v}$ to get $\boldsymbol{u} = T(\boldsymbol{v})$ then I can always find $\boldsymbol{v}$ again through another transformation, called the *inverse* transformation: $\boldsymbol{v} = T^{-1}(\boldsymbol{u})$.

Many times we will be talking about transformation from $\mathbb{R}^{n}$ onto itself. In that case, our transformation matrices will be square matrices. Can linear transformations mapping between spaces with different dimensionality be invertible? Not really, unless there are restrictions on the domain and co-domain - they are not truly of different dimensionality.

So for this short course on linear algebra we will focus on $T: \mathbb{R}^{n} \to \mathbb{R}^{n}$, that is, transformations whose matrices are square. Now lets consider the question: when are such transformations invertible?

*Example 1:* Consider the identity transformation $T: \mathbb{R}^{n} \to \mathbb{R}^{n}$, that is, for any $\boldsymbol{v}$ we have $T(\boldsymbol{v}) = \boldsymbol{v}$. Is this invertible? Sure is, and the inverse transformation $T^{-1} = T$ itself! What is the corresponding transformation matrix? The identity matrix!

*Example 2:* Consider the transformation $T: \mathbb{R}^{3} \to \mathbb{R}^{3}$ such that $T(v_1, v_2, v_3) = (v_1, 2 v_2, 3 v_3)$. This transformation is equivalent to a matrix multiplication by the matrix below:

$$
\boldsymbol{M} = 
\begin{bmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3 \\
\end{bmatrix}
$$

Is this transformation invertible? Lets see: any vector $\boldsymbol{v}$ that gets transformed by it results in the following:

$$
\boldsymbol{v} = 
\begin{bmatrix}
v_1 \\
v_2 \\
v_3
\end{bmatrix}
\Rightarrow
\boldsymbol{u} = T(\boldsymbol{v}) = \boldsymbol{M} \boldsymbol{v} =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3 \\
\end{bmatrix}
\begin{bmatrix}
v_1 \\
v_2 \\
v_3
\end{bmatrix}
=
\begin{bmatrix}
v_1 \\
2 v_2 \\
3 v_3
\end{bmatrix}
$$

So, given the transformed vector $\boldsymbol{u}$, can we find another transform that recreates the original vector $\boldsymbol{v}$? Yes, we can. The inverse transformation is simply dividing the components by the factors that got applied by $T$, that is:

$$
T(\boldsymbol{v}) = (v_1, 2 v_2, 3 v_3) \Rightarrow T^{-1}(\boldsymbol{u}) = (u_1, \frac{1}{2} u_2, \frac{1}{3} u_3)
$$

Composing $T^{-1}$ with $T$ gives the following transform:

$$
(T^{-1} \circ T)(\boldsymbol{v}) = T^{-1}(T(\boldsymbol{v})) =  T^{-1}(\underbrace{v_1, 2 v_2, 3 v_3}_{\boldsymbol{u} = T(\boldsymbol{v})}) = (v_1, \frac{1}{2} \cdot 2 v_2, \frac{1}{3} \cdot 3 v_3) = \boldsymbol{v}
$$


The matrix that reverses the work of $T$ is called the *inverse matrix* of $\boldsymbol{M}$, written $\boldsymbol{M}^{-1}$:

$$
\boldsymbol{M}^{-1} = 
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1/2 & 0 \\
0 & 0 & 1/3
\end{bmatrix}
$$

When we compose $T$ with $T^{-1}$ we are multiplying $\boldsymbol{M}$ by $\boldsymbol{M}^{-1}$ and we get the identity matrix:


$$
\boldsymbol{M}^{-1} \boldsymbol{M} = 
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1/2 & 0 \\
0 & 0 & 1/3
\end{bmatrix}
\begin{bmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3 \\
\end{bmatrix}
= 
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
= \boldsymbol{I}^{(3)}
$$

*Example 3:* Now what about this: $T(\boldsymbol{v}) = (v_1, v_2, 0)$? Imagine that we transform the vector $\boldsymbol{v} = (1, 2, 3)$ - we get $\boldsymbol{u} = T(\boldsymbol{v}) = (1, 2, 0)$. Can we recover the last component of $\boldsymbol{v}$ from $\boldsymbol{u}$? Not at all! The information is lost! This transformation is *not invertible*.


---

**Exercise** What are the inverse transforms (if exists) of the following linear transformations $T: \mathbb{R}^{3} \to \mathbb{R}^3$:

(a) $T(\boldsymbol{v}) = (v_2, v_3, v_1)$

(b) $T(\boldsymbol{v}) = (v_1, v_2, (v_1 + v_2))$

(c) $T(\boldsymbol{v}) = ((v_1 + v_2 + v_3, (v_2 + v_3), v_3)$

---


## Determinants

The determinant of a matrix is a function that *~~was created to make highschoolers miserable~~* assigns a real number to a real-valued square matrix such that:

- The determinant of the identity matrix is 1.
- The exchange of two rows multiplies the determinant by −1.
- Multiplying a row by a number multiplies the determinant by this number.
- Adding a multiple of one row to another row does not change the determinant.

This is a somewhat curious list of properties, but with some geometrical intuition we will finally understand the meaning and utility of the determinant!

First, the elephant in the room: why, oh why, did we have to learn the "Laplace expansion along the $i^{\text{th}}$ row" for the determinant? Just *~~to trigger PTSD~~* as a reminder, the formula was:

$$
\det \boldsymbol{A} = \sum_{j=1}^{n} (-1)^{i + j} a_{i,j} M_{i,j}
$$

where $M_{i,j}$, called the $(i,j)$-*minor* of $\boldsymbol{A}$, is the determinant of the submatrix of $\boldsymbol{A}$ obtained from removing the $i$-th row and the $j$-th column of it. This is not really a very effective way to compute the determinant, at all! Even worse, the formula for the *inverse matrix* (more on this entity in a short bit) is given *~~by Cthulhu himself~~* as follows:

$$
\boldsymbol{A}^{-1} = \frac{1}{\det \boldsymbol{A}} \text{adj} \boldsymbol{A}
$$

where $\text{adj} \boldsymbol{A}$ is the *adjugate (or adjoint, in British English) matrix*, made of the minors of $\boldsymbol{A}$. These concepts are *~~cruelty to students, professors, and little defenseless animals~~* mostly useful for abstract demonstrations. They can be practical, however, for specialized matrices (e.g. the Vandermonde matrix). So we will not bother with them: minors and adjugates should *~~go to \<bleep\>~~* be left to the more abstract mathematicians for now.

Yes, they did traumatize me! (Sad professor noises... trying to reach poor student-self in the past to tell him that it will be ok... determinants will not bite me in the dark... not anymore...)

But that is because I've have never *~~seen the light!~~* been shown the determinant for its properties. And the main one is: ***the determinant of a matrix shows the signed volume change that its linear transformation causes***!

Lets see an example: suppose I have a $2 \times 2$ matrix $\boldsymbol{A}$ that I can use to transform objects in $\mathbb{R}^{2}$ (by transforming every point of the object):

$$
\boldsymbol{A} = 
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

Lets also consider the change $\boldsymbol{A}$ causes to the canonical basis vectors:

$$
\left\{
\boldsymbol{A} = 
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}, 
\boldsymbol{e}^{(1)} =
\begin{bmatrix}
1 \\
0
\end{bmatrix}, 
\boldsymbol{e}^{(2)} =
\begin{bmatrix}
0 \\
1
\end{bmatrix}
\right\}
\Rightarrow
\left\{
\boldsymbol{A} \boldsymbol{e}^{(1)} =
\begin{bmatrix}
a \\
c
\end{bmatrix}, 
\boldsymbol{A} \boldsymbol{e}^{(2)} =
\begin{bmatrix}
b \\
d
\end{bmatrix}
\right\}
$$

Now think of the "diamond" formed by the canonical basis vectors. The "volume" (i.e. the area in the $\mathbb{R}^{2}$ case) is $1$:

<img src="canonical_area.png" width=25%/>

And look at transformed vectors:

<img src="transformed_area.png" width=33%/>

Lets try to make a diamond here and calculate its area.

<img src="transformed_area_2.png" width=50%/>

Our diamond is the shape $OPRQ$. We will make a series of transformations to the diamond shape in a way that maintains its area in each transformation. The magic transformation in this case is called "shearing", and it works by sliding the two vertices of one of the edges. Lets shear the shape along the $\overline{PR}$ edge:

<img src="shear_01.png" width=50%/>

The new diamond $OP^{\prime}R^{\prime}Q$ has the same are as the original diamond! Now lets shear along the $\overline{QR^{\prime}}$ edge:

<img src="shear_02.png" width=50%/>

The final shape has the same area as the original $(OPRQ)$ diamond:

<img src="area_det.png" width=50%/>

So, in conclusion, the application of the transformation given by matrix $\boldsymbol{A}$ took a unit square, of area $1$, and made a diamond of area $(ad - bc)$. If you remember your high-school classes, this is exactly the value of the determinant of $\boldsymbol{A}$! As promised, the determinant of the transformation gave the value of the change in "volume"!

Wait: this demonstration is not a proof! What if it was an accident. But it is not: lets review the algebraic properties of the determinant and see what each one does to the volume:

<table width=50%>
<tr>
<th>Algebraic property</th>
<th>Geometrical interpretation</th>
</tr>
<tr>
<td>The determinant of the identity matrix is 1</td>
<td>The identity matrix changes nothing, therefore the volume of the object stays the same</td>
</tr>
<tr>
<td>Adding a multiple of one row to another row does not change the determinant.</td>
<td>This is the <em>shearing</em> operation, and it does not change the volume!</td>
</tr>
<tr>
<td>Multiplying a row by a number multiplies the determinant by this number</td>
<td>This is equivalent to stretching the diamond in one direction. The stretch factor ends up multiplying the volume of the diamond. 

<p>If the stretch number is negative we get a "reversal" of the shape, and so we will adopt a <em>negative</em> volume in this case - all it means is that the diamond got turned "inside-out"</td>
</tr>
<tr>
<td> The exchange of two rows multiplies the determinant by −1. </td>
<td> Again, this is turning the diamond "inside-out" by swapping the directions. So the area is kept, but with the opposite sign</td>
</tr>
</table>

With all this presentation we can now assert our definition of the determinant in geometrical terms: 

- (As a diamond shape) The determinant of a matrix $\boldsymbol{A}$ is the *signed volume* of the diamond made with its columns.

- (As a transformation) The determinant of a matrix $\boldsymbol{A}$ is the factor of change of *signed volume* that the transformation given by $\boldsymbol{A}$ causes to an object.


## Some special matrices and their determinants

### The identity matrix

This was already given as a property.

### The diagonal matrix

A diagonal matrix is made of zeros everywhere except in the diagonal:

$$
\boldsymbol{\Sigma} = 
\begin{bmatrix}
\sigma_1 & 0 & \cdots & 0 \\
0 & \sigma_2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & \sigma_n
\end{bmatrix}
$$


---

**Exercise** Prove that the determinant of a diagonal matrix is the product of the diagonal elements:

$$
\det \boldsymbol{\Sigma} =
\begin{vmatrix}
\sigma_1 & 0 & \cdots & 0 \\
0 & \sigma_2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & \sigma_n
\end{vmatrix} = \sigma_1 \sigma_2 \cdots \sigma_n
$$

(the vertical bars in place of the usual brackets mean "determinant")

Hint: how can you take an identity matrix and apply the row-transformation properties of the determinant to arrive at the diagonal matrix?

---

### The transpose matrix

Given a square matrix $\boldsymbol{A}$, the determinant of $\boldsymbol{A}^{T}$ is equal to the determinant of $\boldsymbol{A}$. This is a bit hard to prove now, but with the *Singular Value Decomposition* (more on it later) it is almost automatic to show.

### The unitary matrix

Consider a square matrix $\boldsymbol{U}$ represented below in in block form by columns:

$$
\boldsymbol{U} = 
\begin{bmatrix}
\rule[-2ex]{0.5pt}{4ex} & \rule[-2ex]{0.5pt}{4ex} & & \rule[-2ex]{0.5pt}{4ex} \\[1pt]
\boldsymbol{u}^{(1)} & \boldsymbol{u}^{(2)} & \cdots & \boldsymbol{u}^{(n)} \\[1pt]
\rule[-2ex]{0.5pt}{4ex} & \rule[-2ex]{0.5pt}{4ex} & & \rule[-2ex]{0.5pt}{4ex} \\[1pt]
\end{bmatrix}
$$

This matrix is called *unitary* or *orthonormal* if the following properties hold:

- The columns are *unit vectors*, or *versors*: $\lVert \overrightarrow{u}^{(i)} \rVert = 1$

- The columns are all orthogonal to each other: $\overrightarrow{u}^{(i)} \cdot \overrightarrow{u}^{(j)} = 0$ (or $[\boldsymbol{u}^{(i)}]^T [\boldsymbol{u}^{(j)}] = 0$ in matrix notation) whenever $i \neq j$

The absolute value of the determinant of a unitary matrix is $1$. Why is that? Consider that the diamond made with the columns of $\boldsymbol{U}$ has the following characteristics:

- The edges have length $1$

- The edges converging onto any corner are all perpendicular to each other

This is a (hyper-)cube! Therefore the volume is the product of the lengths of the edges, which is $1$.

The only thing missing is the ambiguity about the order of the rows: if we swap two rows we do not change the magnitude of the columns-as-vectors, but we do swap the axis of the hypercube, thus changing the sign of the determinant. So, in any case, the absolute value is still $1$.

### Triangular matrices

A triangular matrix is a square matrix that is filled with zeros either below the diagonal (an *upper-triangular* matrix) or above the diagonal (a *lower-triangular* matrix). Here is an example of a lower-triangular matrix:

$$
\boldsymbol{L} = 
\begin{bmatrix}
l_{1,1} & 0 & \cdots & 0 \\
l_{2,1} & l_{2,2} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
l_{n,1} & l_{n,2} & \cdots & l_{n, n}
\end{bmatrix}
$$

The determinant of a triangular matrix is the product of the diagonal elements:

$$
\det \boldsymbol{L} = 
\begin{vmatrix}
l_{1,1} & 0 & \cdots & 0 \\
l_{2,1} & l_{2,2} & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
l_{n,1} & l_{n,2} & \cdots & l_{n, n}
\end{vmatrix} =
l_{1,1} l_{2,2} \cdots l_{n, n}
$$


---

**Exercise** Prove that the determinant of a lower-triangular matrix is the product of the diagonal elements. Hint: apply the "shearing" transformation many times to zero-out all elements below the diagonal on the first column, then repeat to zero-out all elements below the diagonal on the second column, and so on. What does the final result look like?

---

## When is a transformation invertible? Matrices, determinants, and inverse matrices

## Singular Value Decomposition

Now we are ready for the Singular Value Decomposition (SVD). What we want to do is to decompose a matrix $\boldsymbol{X} \in \mathbb{R}^{m \times n}$, $m \gg n$ into a product of three matrices: $\boldsymbol{U} \in \mathbb{R}^{m \times m}$, $S \in \mathbb{R}^{m \times n}$, and $V^{T} \in \mathbb{R}^{n \times n}$ such that:

- $\boldsymbol{X} = \boldsymbol{U} \boldsymbol{S} \boldsymbol{V}^{T}$
- Matrices $\boldsymbol{U}$ and $\boldsymbol{V}$ are unitary: 
    - $\boldsymbol{U}^{T} \boldsymbol{U} = \boldsymbol{U} \boldsymbol{U}^{T} = \boldsymbol{I}^{(m)}$ is the identity matrix of size $m$
    - $\boldsymbol{V}^{T} \boldsymbol{V} = \boldsymbol{V} \boldsymbol{V}^{T} = \boldsymbol{I}^{(n)}$ is the identity matrix of size $n$
- Matrix $S$ is formed by two vertically stacked blocks (since $m \gg n$):
    - The top block is a diagonal matrix $\Sigma \in \mathbb{R}^{n \times n}$. The diagonal elements are all non-negative (i.e. are positive or zero) and placed in decreasing order. These numbers are the *singular values* of $\boldsymbol{X}$
    - The bottom block is a matrix of zeros, of size $(m - n) \times n$